use_frameworks!

platform :ios, '16.0'

target 'DIContainer_Example' do
  pod 'DIContainer', :path => '../'

  target 'DIContainer_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
