
# .github/settings.yml 示例
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["build-and-test"]
      enforce_admins: true
      restrictions:
        users: []
        teams: ["admins"]

  - name: dev
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["build-and-test"]
      restrictions:
        users: []
        teams: ["dev-team"]

  - name: release/*
    protection:
      required_status_checks:
        strict: true
        contexts: ["build-and-test"]
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions:
        users: []
        teams: ["release-managers"]

  - name: hotfix/*
    protection:
      required_status_checks:
        strict: true
        contexts: ["build-and-test"]
      restrictions:
        users: []
        teams: ["admins"]
