repository:
  name: your-ios-open-source-project
  description: An open-source iOS project with CI/CD and protected branching.
  private: false
  has_issues: true
  has_wiki: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["Build app target", "Run unit tests"]
      enforce_admins: true
      restrictions:
        users: []
        teams: ["admins"]

  - name: dev
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["Build app target", "Run unit tests"]
      restrictions:
        users: []
        teams: [""]

  - name: release/*
    protection:
      required_status_checks:
        strict: true
        contexts: ["Build app target", "Run unit tests"]
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions:
        users: []
        teams: ["release-managers"]

  - name: hotfix/*
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["Build app target", "Run unit tests"]
      restrictions:
        users: []
        teams: ["admins"]

  # feature branches are used for development and do not require protection
  - name: feature/*
  
