name: CD

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  build-and-test:
    if: github.event.action != 'closed'
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app  # 或根据需要更换版本

      - name: Install Dependencies
        run: |
          brew install cocoapods # 如果你用 CocoaPods
          pod install

      - name: Build
        run: |
            cd Example
            xcodebuild build \
              -workspace DIContainer.xcworkspace \
              -scheme DIContainer-Example \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
              -configuration Debug \
              -xcconfig DisableSigning.xcconfig

      - name: Run Tests
        run: |
            cd Example
            xcodebuild test \
              -workspace DIContainer.xcworkspace \
              -scheme DIContainer-Example \
              -only-testing:DIContainer_Tests \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
              -configuration Debug \
              -xcconfig DisableSigning.xcconfig

  auto-tag:
    if: github.event.pull_request.merged == true && github.event.action == 'closed' && startsWith(github.head_ref, 'release/')
    runs-on: macos-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get tag from branch
        id: get_tag
        run: |
          branch="${{ github.head_ref }}"
          version="${branch#release/}"
          tag="v$version"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin ${{ steps.get_tag.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
          body: "Auto-generated release for ${{ steps.get_tag.outputs.tag }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
