name: CD - Auto Merge dev -> main on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify tag source branch is dev
        run: |
          git fetch origin dev
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          DEV_COMMIT=$(git rev-parse origin/dev)
          if [ "$TAG_COMMIT" != "$DEV_COMMIT" ]; then
            echo "❌ Tag must be created from the tip of dev branch."
            exit 1
          fi

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Merge dev into main
        run: |
          git checkout main
          git merge origin/dev --no-ff -m "Auto-merge dev into main on tag ${{ github.ref_name }}"
          git push origin main
